# Ultralytics ðŸš€ AGPL-3.0 License - https://ultralytics.com/license

blank_issues_enabled: true
contact_links:
  - name: ðŸ“„ Docs
    url: https://docs.ultralytics.com/
    about: Full Ultralytics YOLO Documentation
  - name: ðŸ”— Replicate Docs
    url: https://replicate.com/docs
    about: Official Replicate Documentation
  - name: ðŸ’¬ Forum
    url: https://community.ultralytics.com/
    about: Ask on Ultralytics Community Forum
  - name: ðŸŽ§ Discord
    url: https://ultralytics.com/discord
    about: Ask on Ultralytics Discord
